import { PackageDropPlace } from '../../enums/package_drop_place';
import { OrderDeliveryBoxReadResponse } from '../order_delivery_box/responses/order_delivery_box_read_response';
import { OrderPickProductReadResponse } from '../order_pick_product/responses/order_pick_product_read_response';
import { OrderStatusChangeHistoryReadResponse } from '../order_status_change_history/responses/order_status_change_history_read_response';
import { AddressDto } from './address_dto';
import { AppDateDto } from './app_date_dto';
import { AppTimeDto } from './app_time_dto';
import { AppTimePeriodDto } from './app_time_period_dto';
import { CouponCodeDto } from './coupon_code_dto';
import { DeliveryNumberDto } from './delivery_number_dto';
import { OrderDetailExt } from './order_detail_ext';
import { PostalDto } from './postal_dto';
import { PriceSetDto } from './price_set_dto';
import { ReceiptNumberDto } from './receipt_number_dto';
import { TelDto } from './tel_dto';
export interface OrderSummaryExt{

  order_summary_id: string;
  user_id: string;
  user_name: string;
  estimate_price_set: PriceSetDto;
  settlement_price_set: PriceSetDto;
  order_date_time: Date;
  order_date: AppDateDto;
  receipt_date: AppDateDto;
  sales_recorded_date: AppDateDto;
  order_memo: string;
  receiving_method: number;
  delivery_type: number;
  receipt_number: ReceiptNumberDto;
  delivery_reservation_id: string;
  postal: PostalDto;
  address: AddressDto;
  tel: TelDto;
  price_calc_method: number;
  tax_calc_method: number;
  delivery_hours: AppTimePeriodDto;
  coupon_code: CouponCodeDto;
  payment_type: number;
  handle_type_for_shortage: number;
  delivery_number: DeliveryNumberDto;
  order_state: string;
  order_details: OrderDetailExt[];
  order_details_settled: OrderDetailExt[];
  order_details_canceled: OrderDetailExt[];
  picked_products: OrderPickProductReadResponse[];
  order_delivery_box: OrderDeliveryBoxReadResponse[];
  change_history: OrderStatusChangeHistoryReadResponse[];
  pickup_time: AppTimeDto;
  delivery_memo: string;
  prefer_drop_place: PackageDropPlace;
  full_name_kana: string;
  payment_flag: number;
  receipt_date_time_desc: string;
  tracking_id: string;
  sbps_transaction_id: string;

}
