import { DeliveryType } from '../../../enums/delivery_type';
import { HandleTypeForShortage } from '../../../enums/handle_type_for_shortage';
import { PackageDropPlace } from '../../../enums/package_drop_place';
import { PaymentFlag } from '../../../enums/payment_flag';
import { PaymentType } from '../../../enums/payment_type';
import { PriceCalcMethod } from '../../../enums/price_calc_method';
import { ReceivingMethod } from '../../../enums/receiving_method';
import { TaxCalcMethod } from '../../../enums/tax_calc_method';
import { AddressDto } from '../../common/address_dto';
import { AppDateDto } from '../../common/app_date_dto';
import { AppTimeDto } from '../../common/app_time_dto';
import { AppTimePeriodDto } from '../../common/app_time_period_dto';
import { CouponCodeDto } from '../../common/coupon_code_dto';
import { DeliveryNumberDto } from '../../common/delivery_number_dto';
import { PostalDto } from '../../common/postal_dto';
import { PriceSetDto } from '../../common/price_set_dto';
import { ReceiptNumberDto } from '../../common/receipt_number_dto';
import { TelDto } from '../../common/tel_dto';
export interface OrderSummaryCreateRequest{

  parent_store_id: string;
  user_id: string;
  estimate_price_set: PriceSetDto;
  settlement_price_set: PriceSetDto;
  order_date_time: Date;
  order_date: AppDateDto;
  receipt_date: AppDateDto;
  sales_recorded_date: AppDateDto;
  order_memo: string;
  receiving_method: ReceivingMethod;
  delivery_type: DeliveryType;
  receipt_number: ReceiptNumberDto;
  delivery_reservation_id: string;
  postal: PostalDto;
  address: AddressDto;
  tel: TelDto;
  price_calc_method: PriceCalcMethod;
  tax_calc_method: TaxCalcMethod;
  delivery_hours: AppTimePeriodDto;
  coupon_code: CouponCodeDto;
  pickup_time: AppTimeDto;
  delivery_memo: string;
  payment_flag: PaymentFlag;
  prefer_drop_place: PackageDropPlace;
  sps_transaction_id: string;
  tracking_id: string;
  payment_type: PaymentType;
  handle_type_for_shortage: HandleTypeForShortage;
  delivery_number: DeliveryNumberDto;

}
